### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by gomezgleonardob** [learnbyexample/Python_Basics#10]
Its possible realize the fork and translate to Spanish

**Comment by learnbyexample** [comment]
Yes, you are welcome to fork/clone and modify this repo as you wish, including translation to other languages.

The repo is licensed under https://creativecommons.org/licenses/by-nc-sa/4.0/ (you can read a Spanish version at https://creativecommons.org/licenses/by-nc-sa/4.0/deed.es_ES) which allows you to do so.

**Comment by gomezgleonardob** [comment]
Thanks fork is released :D , I start the translation

**Comment by learnbyexample** [comment]
Cool, let me know once you've finished :)

And do feel free to ping me if there are doubts or if you find an error/typo/etc
